### ISSUE TITLE
Add .fw file to the releases

### ISSUE THREAD

**Issue by klundry** [ModusCreateOrg/genus#234]
Would it be possible to add the game as a .fw file to the releases to make flashing it on an odroid go easier?

**Comment by jaygarcia** [comment]
Hi @klundry yes, this is a great idea!  

I'm currently upgrading the game and a snapshot of creative-engine to support ESP-IDF4.0

**Comment by jaygarcia** [comment]
We've moved the codebase from supporting the ODROID GO. :(

**Comment by klundry** [comment]
Aww, that is a bummer.

**Comment by jaygarcia** [comment]
yeah dude. :(. we made that decision partially b/c the latest GO SDK became wildly incompatible with the versions we had used when we released the game.
